spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: file://Users/neenad/codes/tutorials/java/movie-demo-spring/config-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
    instance:
      leaseRenewalIntervalInSeconds: 5